mongohost:
  image: mongo
  volumes:
    - mongodata:/data/db
  volume_driver: convoy

api1:
  image: aalferez/api
  volumes:
    - musicdata:/API/public/media
  volume_driver: convoy

api2:
  image: aalferez/api
  volumes:
    - musicdata:/API/public/media
  volume_driver: convoy

api3:
  image: aalferez/api
  volumes:
    - musicdata:/API/public/media
  volume_driver: convoy

balancer:
  build: Backend/LoadBalancer
  links:
    - api1
    - api2
    - api3
  ports:
    - "7070:7070"
    - "3000:3000"

web1:
  image: aalferez/app
  links:
    - balancer
    - mongohost
  ports:
    - "8002:8080"
